"""added subject column to the Comment table.

Revision ID: 5fde95b52fc8
Revises: 717807c30a01
Create Date: 2023-08-01 11:57:19.070812

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fde95b52fc8'
down_revision = '717807c30a01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subject', sa.Text(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_column('subject')

    # ### end Alembic commands ###
